{"name": "test_create_dashboard", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидался 201, получен 404. Ответ: {\"timestamp\":\"2025-04-02T18:11:17.704+00:00\",\"status\":404,\"error\":\"Not Found\",\"path\":\"/api/v1/dashboard\"}\nassert 404 == 201\n +  where 404 = <Response [404]>.status_code", "trace": "def test_create_dashboard():\n        response = requests.post(\n            f\"{BASE_URL}\",\n            headers={\n                \"Authorization\": f\"Bearer {API_KEY}\",\n                \"Content-Type\": \"application/json\"\n            },\n            json={\n                \"name\": \"MyTestDashboard\",\n                \"description\": \"Test dashboard\"\n            }\n        )\n        print(response.text)  # Для диагностики\n>       assert response.status_code == 201, f\"Ожидался 201, получен {response.status_code}. Ответ: {response.text}\"\nE       AssertionError: Ожидался 201, получен 404. Ответ: {\"timestamp\":\"2025-04-02T18:11:17.704+00:00\",\"status\":404,\"error\":\"Not Found\",\"path\":\"/api/v1/dashboard\"}\nE       assert 404 == 201\nE        +  where 404 = <Response [404]>.status_code\n\ntest_api.py:20: AssertionError"}, "attachments": [{"name": "stdout", "source": "43296f2b-55e0-41d7-bcfb-b9e0ed44c021-attachment.txt", "type": "text/plain"}], "start": 1743617432359, "stop": 1743617432747, "uuid": "e2bdf4e4-2bca-46ed-a0d8-f4ee4b7ba9ef", "historyId": "23d982c0770c411de99a149b666b03b0", "testCaseId": "23d982c0770c411de99a149b666b03b0", "fullName": "test_api#test_create_dashboard", "labels": [{"name": "suite", "value": "test_api"}, {"name": "host", "value": "DESKTOP-A6SUBLI"}, {"name": "thread", "value": "16736-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api"}]}